import Home from "./home/home";
import Purchases from "./purchase/purchase";
import Sales from "./sales/sales";
import Customer from "./customers/customer";
import Suppliers from "./suppliers/suppliers";
import Cashbook from "./cashbook/cashbook";
// import Login from "./login";
import Login from "./login";
import Sighup from "./sighup";
import Setting from "./setting/setting";
export { Home, Purchases, Sales, Suppliers, Cashbook, Customer, Sighup, Login,Setting };
